version: '3'

services:
    php:
      build: .
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./:/var/www
        - ./dockerdata/apache2/apache2.conf:/etc/apache2/apache2.conf
      links:
        - db

      depends_on:
        - db
    db:
      image: mysql:5.7
      expose:
        - 3306
      ports:
        - 3306:3306
      volumes:
        - ./dockerdata/dbmysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=meubanco
        - MYSQL_ROOT_PASSWORD=passroot
        - MYSQL_USER=user
