name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  name: laravel install
  runs-on: ubuntu-latest

  steps:
     with:
        php-version: '8.1'
    uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    name: instalando dependencias - composer
      run: composer install
