name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  intação-laravel:

    runs-on: ubuntu-latest

    steps:

      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Instalação de dependfencias
        run: composer install
    - name: Generate key
        run: php artisan key:generate
    - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
    - name: install npm
        run: npm install
    - name: build npm
      run: npm run prod

